version : "3"
services:
  backend:
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DATABASE_DSN: ${DATABASE_DSN}
    command: ["go", "run", "cmd/server/main.go"]

  database:
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - "./misc/sql:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
