name: Docker Build & Push

on:
  push:
    branches:
      - '**'
    pull_request:
      branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build & Push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/seccamp-2023-backend:latest
            ghcr.io/${{ github.actor }}/seccamp-2023-backend:${{ github.sha }}
